/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package zango.demo.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Produit service. Represents a row in the &quot;ZANGO_Produit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link zango.demo.core.model.impl.ProduitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link zango.demo.core.model.impl.ProduitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Produit
 * @see zango.demo.core.model.impl.ProduitImpl
 * @see zango.demo.core.model.impl.ProduitModelImpl
 * @generated
 */
@ProviderType
public interface ProduitModel extends BaseModel<Produit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a produit model instance should use the {@link Produit} interface instead.
	 */

	/**
	 * Returns the primary key of this produit.
	 *
	 * @return the primary key of this produit
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this produit.
	 *
	 * @param primaryKey the primary key of this produit
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id produit of this produit.
	 *
	 * @return the id produit of this produit
	 */
	public int getIdProduit();

	/**
	 * Sets the id produit of this produit.
	 *
	 * @param idProduit the id produit of this produit
	 */
	public void setIdProduit(int idProduit);

	/**
	 * Returns the lib of this produit.
	 *
	 * @return the lib of this produit
	 */
	@AutoEscape
	public String getLib();

	/**
	 * Sets the lib of this produit.
	 *
	 * @param lib the lib of this produit
	 */
	public void setLib(String lib);

	/**
	 * Returns the prix of this produit.
	 *
	 * @return the prix of this produit
	 */
	public long getPrix();

	/**
	 * Sets the prix of this produit.
	 *
	 * @param prix the prix of this produit
	 */
	public void setPrix(long prix);

	/**
	 * Returns the date mise vente of this produit.
	 *
	 * @return the date mise vente of this produit
	 */
	@AutoEscape
	public String getDateMiseVente();

	/**
	 * Sets the date mise vente of this produit.
	 *
	 * @param dateMiseVente the date mise vente of this produit
	 */
	public void setDateMiseVente(String dateMiseVente);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(zango.demo.core.model.Produit produit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<zango.demo.core.model.Produit> toCacheModel();

	@Override
	public zango.demo.core.model.Produit toEscapedModel();

	@Override
	public zango.demo.core.model.Produit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}